version: '3.8'
services:
  app:
    image: codemask:latest
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./src:/app/src
    networks:
      - codemask
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: codemask_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - codemask

networks:
  codemask: